#! /usr/bin/env bash
dt=`date +%y-%m-%d | sed -E "s@$((12+1))@12_01@" | sed -E "s@(\d)$((5+1))@\\15_01@" | sed "s@$((5+1))@5_01@"`
if [ "$1" == "dashed" ]; then
echo $dt
else
echo $dt | sed "s@-@@g"
fi