#! /usr/bin/env bash
. cdsynt
cd db/_backups
if [ "$1" != "--nodate" -a "$1" != "nodate" -a "$1" != "nodt" -a "$1" != "--nodt" -a "$1" != "nodt" ]; then
dt=`sbdate`
mkdir -p $dt
cd $dt
echo "No --nodate param passed so cd to $dt."
else 
echo "--nodate param passed so cd to `pwd`."
fi
echo "Cur dir: `pwd`"
